matrix:
  include:
    - os: linux
      dist: trusty
      rust: 1.12.1
      env: TARGET=x86_64-unknown-linux-gnu
sudo: required
language: rust
addons:
  apt:
    packages:
    - cmake
    - qt5-default
    - qtdeclarative5-dev
    - qtbase5-private-dev
    - libqt5svg5-dev
    - pkg-config
    - git
    - build-essential
    - xvfb
before_install: |
  sudo apt-get -qq install qtdeclarative5-qtquick2-plugin qtdeclarative5-window-plugin libqt5qml-quickcontrols
  export DISPLAY=:99.0
  sh -e /etc/init.d/xvfb start
script: |
  cargo build --verbose
  RUST_TEST_THREADS=1 cargo test --verbose
